[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"
  USE_FULL_RESOLUTION_IMAGES = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

